/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function add(a: number, b: number): number
export function subtract(a: number, b: number): number
export function multiply(a: number, b: number): number
export function divide(a: number, b: number): number
export function ceil(num: number, precision: number): number
export function floor(num: number, precision: number): number
export function round(value: number, decimalPlaces: number): number
export function sum(nums: Array<number>): number
export function max(nums: Array<number>): number | null
export function min(nums: Array<number>): number | null
