/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function add(a: number, b: number): number
export function divide(a: number, b: number): number
export function ceil(num: number, precision: number): number
export function floor(num: number, precision: number): number
